# 配列の作成

## 1次元配列

In [1]:
[1]

1-element Array{Int64,1}:
 1

In [2]:
[1 , 3 , 4]

3-element Array{Int64,1}:
 1
 3
 4

In [3]:
Float16[1 , 3  ,4]

3-element Array{Float16,1}:
 1.0
 3.0
 4.0

In [4]:
Float32[1 , 3 , 4]

3-element Array{Float32,1}:
 1.0
 3.0
 4.0

In [5]:
Float64[1 , 3  , 4]

3-element Array{Float64,1}:
 1.0
 3.0
 4.0

In [6]:
Vector(1:5)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [7]:
Vector(1:2:5) #start:step:end

3-element Array{Int64,1}:
 1
 3
 5

In [8]:
Array(1:2:5)

3-element Array{Int64,1}:
 1
 3
 5

In [9]:
[1:2:5;]

3-element Array{Int64,1}:
 1
 3
 5

In [10]:
collect(1:2:5)

3-element Array{Int64,1}:
 1
 3
 5

In [11]:
[i for i in 1:2:5]

3-element Array{Int64,1}:
 1
 3
 5

## 2次元配列

In [12]:
[1 3 4]

1×3 Array{Int64,2}:
 1  3  4

In [13]:
[1 2 ; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [14]:
[1 2
 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [15]:
[1 2 ;
 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [16]:
[1; 3; 5]

3-element Array{Int64,1}:
 1
 3
 5

## 単位行列

In [17]:
using LinearAlgebra

In [18]:
Matrix(1.0I , 3 , 3)

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [19]:
Matrix{Int32}(1I , (3 , 3))

3×3 Array{Int32,2}:
 1  0  0
 0  1  0
 0  0  1

In [20]:
Array(1I , (3 , 3))

3×3 Array{Int64,2}:
 1  0  0
 0  1  0
 0  0  1

In [21]:
collect(1I(3))

3×3 Array{Int64,2}:
 1  0  0
 0  1  0
 0  0  1

In [22]:
a = rand(3 , 3)
one(a)

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [23]:
b = rand(Int32, 2 , 2)
oneunit(b)

2×2 Array{Int32,2}:
 1  0
 0  1

## ベクトルから行列に

In [24]:
a = Vector(1:3)

3-element Array{Int64,1}:
 1
 2
 3

In [25]:
a[: , :] #軸追加

3×1 Array{Int64,2}:
 1
 2
 3

In [26]:
b = Vector(4:6)
[a b]

3×2 Array{Int64,2}:
 1  4
 2  5
 3  6

## n次元配列

### 全要素0の配列

In [27]:
zeros(1)

1-element Array{Float64,1}:
 0.0

In [28]:
zeros(2 , 2)

2×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0

In [29]:
zeros((2 , 2))

2×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0

In [30]:
zeros(Int32 , (3 , 2 , 1))

3×2×1 Array{Int32,3}:
[:, :, 1] =
 0  0
 0  0
 0  0

In [31]:
zeros(Int32 , (3 , 2))

3×2 Array{Int32,2}:
 0  0
 0  0
 0  0

In [32]:
a = rand(2 , 2)

2×2 Array{Float64,2}:
 0.950213  0.19887 
 0.967714  0.424811

In [33]:
zero(a)

2×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0

### 全要素1の配列

In [34]:
ones(Int8, (3 , 2 , 1))

3×2×1 Array{Int8,3}:
[:, :, 1] =
 1  1
 1  1
 1  1

In [35]:
ones(Int8, (3 , 2))

3×2 Array{Int8,2}:
 1  1
 1  1
 1  1

### 任意の値で初期化した配列

In [36]:
fill(3 , 2 , 2) #fill(任意の値 , 行 , 列)

2×2 Array{Int64,2}:
 3  3
 3  3

In [37]:
fill(5.0 , (2 , 2 , 1))

2×2×1 Array{Float64,3}:
[:, :, 1] =
 5.0  5.0
 5.0  5.0

### 未初期化の配列

In [38]:
Vector{Int32}(undef , 3) # 1次元配列

3-element Array{Int32,1}:
 -1
 -1
  1

In [39]:
Matrix{Float64}(undef , 2 , 3) #2次元配列

2×3 Array{Float64,2}:
 2.25452e-314  2.15822e-314  2.15825e-314
 2.2183e-314   2.25845e-314  0.0         

In [40]:
Array{Float64}(undef , 2 , 3)

2×3 Array{Float64,2}:
 2.25845e-314  2.2589e-314   2.25845e-314
 2.1855e-314   2.15823e-314  2.15822e-314

In [41]:
Array{Float32}(undef , (3 , 3 , 1))

3×3×1 Array{Float32,3}:
[:, :, 1] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

# 配列の要素へのアクセス

## 1次元配列

### 一つの要素を取り出す

In [42]:
a = Vector(1:3)

3-element Array{Int64,1}:
 1
 2
 3

In [43]:
a[1]

1

In [44]:
a[3]

3

In [45]:
a[end]

3

In [46]:
a[CartesianIndex(end)]

3

In [47]:
a[CartesianIndex(2 , 1 , 1 , 1)]

2

In [48]:
a[2 , 1 , 1 , 1]

2

### 複数の要素を取り出す

In [49]:
a = Vector(1 : 5)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [50]:
a[1 : end]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [51]:
a[2 : end - 1]

3-element Array{Int64,1}:
 2
 3
 4

In [52]:
a[1 : 2 : end]

3-element Array{Int64,1}:
 1
 3
 5

In [53]:
a[:3] #start , end 片方ではダメ．両方宣言する

3

In [54]:
a[[1 , 2 , 5]]

3-element Array{Int64,1}:
 1
 2
 5

In [55]:
a[[3 , 5 , 3]]

3-element Array{Int64,1}:
 3
 5
 3

In [56]:
a[[CartesianIndex(3) , CartesianIndex(end) , CartesianIndex(3)]]

3-element Array{Int64,1}:
 3
 5
 3

## 2次元配列

### 一つの要素を取り出す

In [57]:
a = [5 6 7 ; 8 9 10]

2×3 Array{Int64,2}:
 5  6   7
 8  9  10

In [58]:
a[1] #Linear Index

5

In [59]:
a[2]

8

In [60]:
a[3]

6

In [61]:
a[4]

9

In [62]:
a[5]

7

In [63]:
a[6]

10

In [64]:
a[1 , 1] #Cartesian Index

5

In [65]:
a[1 , 2]

6

In [66]:
a[1 , 3]

7

In [67]:
a[2  , 1]

8

In [68]:
a[2 , 2]

9

In [69]:
a[2 , 3]

10

In [70]:
a[end]

10

In [71]:
a[end , end]

10

### 複数の要素を取り出す

#### 行や列を1次元配列で

In [72]:
a = reshape(1:9 , (3,3))

3×3 reshape(::UnitRange{Int64}, 3, 3) with eltype Int64:
 1  4  7
 2  5  8
 3  6  9

In [73]:
a[: , 1] #Cartesian Index

3-element Array{Int64,1}:
 1
 2
 3

In [74]:
a[2 , :] #Cartesian Index

3-element Array{Int64,1}:
 2
 5
 8

In [75]:
a[[2 , 5 , 8]]

3-element Array{Int64,1}:
 2
 5
 8

In [76]:
a[[CartesianIndex(2 , 1) , CartesianIndex(2 , 2) , CartesianIndex(2 , 3)]]

3-element Array{Int64,1}:
 2
 5
 8

In [77]:
a[CartesianIndex.(2 , 1:3)] #ブロードキャスト

3-element Array{Int64,1}:
 2
 5
 8

#### 行や列を2次元配列で

In [78]:
a = reshape(1:9 , (3,3))

3×3 reshape(::UnitRange{Int64}, 3, 3) with eltype Int64:
 1  4  7
 2  5  8
 3  6  9

In [79]:
a[: , 2:end]

3×2 Array{Int64,2}:
 4  7
 5  8
 6  9

In [80]:
a[: , 1:1]

3×1 Array{Int64,2}:
 1
 2
 3

In [81]:
a[1:2 , :]

2×3 Array{Int64,2}:
 1  4  7
 2  5  8

In [82]:
a[2:2 , :]

1×3 Array{Int64,2}:
 2  5  8

#### 正方行列の対角成分のみ

In [83]:
a = [1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [84]:
a[CartesianIndex.(1:1 , 1:2)] #対角行列

2-element Array{Int64,1}:
 1
 2

In [85]:
a[CartesianIndex.(1:2, 2:-1:1)] #反対角行列

2-element Array{Int64,1}:
 2
 3

In [86]:
diag(a) #対角行列

2-element Array{Int64,1}:
 1
 4

## n次元配列

### 条件を満たす部分を取り出す

In [87]:
a = reshape(1:9 , (3 , 3))

3×3 reshape(::UnitRange{Int64}, 3, 3) with eltype Int64:
 1  4  7
 2  5  8
 3  6  9

In [88]:
a[a .< 5]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [89]:
a[a .> 5]

4-element Array{Int64,1}:
 6
 7
 8
 9

In [90]:
a[a .== 5]

1-element Array{Int64,1}:
 5

In [91]:
a[3 .< a .<= 7]

4-element Array{Int64,1}:
 4
 5
 6
 7

### フィルターを使って偶奇

In [92]:
a = reshape(1:9 , (3 , 3))

3×3 reshape(::UnitRange{Int64}, 3, 3) with eltype Int64:
 1  4  7
 2  5  8
 3  6  9

In [93]:
filter(isodd , a)

5-element Array{Int64,1}:
 1
 3
 5
 7
 9

In [94]:
filter(iseven , a)

4-element Array{Int64,1}:
 2
 4
 6
 8

## 配列の要素に代入する

複数の要素への代入はブロードキャスト`.`を使用する。

### 1次元配列

In [95]:
a = Vector(1:4)

4-element Array{Int64,1}:
 1
 2
 3
 4

In [96]:
a[2] = 0
a

4-element Array{Int64,1}:
 1
 0
 3
 4

In [97]:
a[a .< 4] .= 0
a

4-element Array{Int64,1}:
 0
 0
 0
 4

In [98]:
b = a
b[end] = 0
a

4-element Array{Int64,1}:
 0
 0
 0
 0

### 2次元配列

In [99]:
a = [1 2 3 ; 4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [100]:
a[1 , :] .= 0
a

2×3 Array{Int64,2}:
 0  0  0
 4  5  6

In [101]:
a[: , 2:end] .= 2
a

2×3 Array{Int64,2}:
 0  2  2
 4  2  2

In [102]:
a[a .== 2] .= 3
a

2×3 Array{Int64,2}:
 0  3  3
 4  3  3

In [103]:
a .= 1

2×3 Array{Int64,2}:
 1  1  1
 1  1  1

In [104]:
a = reshape(1:6 , (2 , 3)) #reshape

2×3 reshape(::UnitRange{Int64}, 2, 3) with eltype Int64:
 1  3  5
 2  4  6

In [105]:
a[1 , 1] = 0 #Array ではないので代入できない

ErrorException: indexed assignment fails for a reshaped range; consider calling collect

In [106]:
a = Array(a) #Array に変換

2×3 Array{Int64,2}:
 1  3  5
 2  4  6

In [107]:
a[1 , 1] = 0
a

2×3 Array{Int64,2}:
 0  3  5
 2  4  6

## 配列の情報を取得する

### 次元数を取得する

In [108]:
a = ones(2 , 3 , 4)

2×3×4 Array{Float64,3}:
[:, :, 1] =
 1.0  1.0  1.0
 1.0  1.0  1.0

[:, :, 2] =
 1.0  1.0  1.0
 1.0  1.0  1.0

[:, :, 3] =
 1.0  1.0  1.0
 1.0  1.0  1.0

[:, :, 4] =
 1.0  1.0  1.0
 1.0  1.0  1.0

In [109]:
ndims(a) #次元数の取得

3

In [110]:
size(a) #形状の取得

(2, 3, 4)

In [111]:
a = [1 , 2 , 3]
length(a) #全要素数の取得

3

In [112]:
b = [1 2 ; 3 4]
length(b)

4

### 型を取得する

In [113]:
a = ones(2 , 3)

2×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [114]:
eltype(a) #要素の型

Float64

In [115]:
typeof(a) #配列の型

Array{Float64,2}

## 配列の形状や次元数の操作をする

In [116]:
a = Vector(1 : 4)

4-element Array{Int64,1}:
 1
 2
 3
 4

In [117]:
reshape(a , 2 , 2)

2×2 Array{Int64,2}:
 1  3
 2  4

In [118]:
reshape(1:4 , (2 , 2 , 1))

2×2×1 reshape(::UnitRange{Int64}, 2, 2, 1) with eltype Int64:
[:, :, 1] =
 1  3
 2  4

## 軸を入れ替える

### 1次元配列と2次元配列(転置)

In [119]:
a = Vector(1 : 3)

3-element Array{Int64,1}:
 1
 2
 3

In [120]:
transpose(a) #行ベクトル

1×3 Transpose{Int64,Array{Int64,1}}:
 1  2  3

In [121]:
a' #transpose(a)と同じ

1×3 Adjoint{Int64,Array{Int64,1}}:
 1  2  3

In [122]:
b = [1 2 ; 3 4 ; 5 6]

3×2 Array{Int64,2}:
 1  2
 3  4
 5  6

In [123]:
transpose(b)

2×3 Transpose{Int64,Array{Int64,2}}:
 1  3  5
 2  4  6

In [124]:
b'

2×3 Adjoint{Int64,Array{Int64,2}}:
 1  3  5
 2  4  6

### n次元配列

In [125]:
a = [1 2 3 ; 4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [126]:
permutedims(a)

3×2 Array{Int64,2}:
 1  4
 2  5
 3  6

In [127]:
permutedims(a , (2  , 1))

3×2 Array{Int64,2}:
 1  4
 2  5
 3  6

In [128]:
b = ones(4 , 5 , 6)

4×5×6 Array{Float64,3}:
[:, :, 1] =
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

[:, :, 2] =
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

[:, :, 3] =
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

[:, :, 4] =
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

[:, :, 5] =
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

[:, :, 6] =
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [129]:
size(b)

(4, 5, 6)

In [130]:
permutedims(b , (2  ,1 , 3))

5×4×6 Array{Float64,3}:
[:, :, 1] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

[:, :, 2] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

[:, :, 3] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

[:, :, 4] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

[:, :, 5] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

[:, :, 6] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

In [131]:
size(permutedims(b , (2  ,1 , 3)))

(5, 4, 6)

## 軸を追加する

### 後ろのみ

In [132]:
a = [1 2 ; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [133]:
a[: , : , :]

2×2×1 Array{Int64,3}:
[:, :, 1] =
 1  2
 3  4

In [134]:
a[: , : , : , :]

2×2×1×1 Array{Int64,4}:
[:, :, 1, 1] =
 1  2
 3  4

### 任意の位置

In [135]:
a = [1 2 ; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [136]:
const newaxis = [CartesianIndex()]

1-element Array{CartesianIndex{0},1}:
 CartesianIndex()

In [137]:
a[: , newaxis , newaxis , :]

2×1×1×2 Array{Int64,4}:
[:, :, 1, 1] =
 1
 3

[:, :, 1, 2] =
 2
 4

## 軸を削除する

In [138]:
a = reshape(1:4 , (2 , 1 , 2 , 1))

2×1×2×1 reshape(::UnitRange{Int64}, 2, 1, 2, 1) with eltype Int64:
[:, :, 1, 1] =
 1
 2

[:, :, 2, 1] =
 3
 4

In [139]:
dropdims(a , dims = 2)

2×2×1 reshape(::UnitRange{Int64}, 2, 2, 1) with eltype Int64:
[:, :, 1] =
 1  3
 2  4

In [140]:
size(dropdims(a , dims = (2 , 4)))

(2, 2)

## n次元配列を1次元配列にする

In [141]:
a = [1 2 ; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [142]:
vec(a)

4-element Array{Int64,1}:
 1
 3
 2
 4

In [143]:
a[:]

4-element Array{Int64,1}:
 1
 3
 2
 4

## 配列の型を変換する

In [144]:
a = [1 2 ; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [145]:
Array{Float32}(a)

2×2 Array{Float32,2}:
 1.0  2.0
 3.0  4.0

In [146]:
b = Vector(1:3)

3-element Array{Int64,1}:
 1
 2
 3

In [147]:
Array{Float16}(b)

3-element Array{Float16,1}:
 1.0
 2.0
 3.0

In [148]:
Vector{Float16}(b)

3-element Array{Float16,1}:
 1.0
 2.0
 3.0

In [149]:
convert(Array{Float16} , b)

3-element Array{Float16,1}:
 1.0
 2.0
 3.0

## 配列同士を結合する

### 縦に結合する

In [150]:
a = ([0 , 1 , 2] , [3 , 4])

([0, 1, 2], [3, 4])

In [151]:
vcat(a...)

5-element Array{Int64,1}:
 0
 1
 2
 3
 4

In [152]:
b = [0 1 2 ; 3 4 5]

2×3 Array{Int64,2}:
 0  1  2
 3  4  5

In [153]:
c = [6 , 7 , 8]'

1×3 Adjoint{Int64,Array{Int64,1}}:
 6  7  8

In [154]:
vcat(b , c) #行列と行ベクトルの結合

3×3 Array{Int64,2}:
 0  1  2
 3  4  5
 6  7  8

In [155]:
vcat(b , b) #行列同士

4×3 Array{Int64,2}:
 0  1  2
 3  4  5
 0  1  2
 3  4  5

In [156]:
cat(b , b  , dims = 1)

4×3 Array{Int64,2}:
 0  1  2
 3  4  5
 0  1  2
 3  4  5

In [157]:
[b ; b]

4×3 Array{Int64,2}:
 0  1  2
 3  4  5
 0  1  2
 3  4  5

### 横に結合する

In [158]:
a = ([0 1 2] , [3 4 5])

([0 1 2], [3 4 5])

In [159]:
hcat(a...)

1×6 Array{Int64,2}:
 0  1  2  3  4  5

In [160]:
b = ([0 , 1 , 2] , [3 , 4 , 5])

([0, 1, 2], [3, 4, 5])

In [161]:
hcat(b...)

3×2 Array{Int64,2}:
 0  3
 1  4
 2  5

In [162]:
c = [0 1 ; 2 3 ; 4 5]

3×2 Array{Int64,2}:
 0  1
 2  3
 4  5

In [163]:
d = [6 , 7 , 8]

3-element Array{Int64,1}:
 6
 7
 8

In [164]:
hcat(c , d)

3×3 Array{Int64,2}:
 0  1  6
 2  3  7
 4  5  8

In [165]:
hcat(c , c)

3×4 Array{Int64,2}:
 0  1  0  1
 2  3  2  3
 4  5  4  5

In [166]:
cat(c , c , dims = 2)

3×4 Array{Int64,2}:
 0  1  0  1
 2  3  2  3
 4  5  4  5

In [167]:
[c c]

3×4 Array{Int64,2}:
 0  1  0  1
 2  3  2  3
 4  5  4  5

## その他

### ソートする

In [168]:
a = [3 , 1 , 4 , 2]

4-element Array{Int64,1}:
 3
 1
 4
 2

In [169]:
sort(a) #昇順

4-element Array{Int64,1}:
 1
 2
 3
 4

In [170]:
sort(a , rev = true) #降順

4-element Array{Int64,1}:
 4
 3
 2
 1

In [171]:
a = [3 1 4 2]

1×4 Array{Int64,2}:
 3  1  4  2

In [172]:
sort(a , dims = 2)

1×4 Array{Int64,2}:
 1  2  3  4

### 逆順にする

In [173]:
a = Vector(0:2)

3-element Array{Int64,1}:
 0
 1
 2

In [174]:
reverse(a)

3-element Array{Int64,1}:
 2
 1
 0

In [175]:
a[end : -1 : 1]

3-element Array{Int64,1}:
 2
 1
 0

In [176]:
a = Vector(1:5)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [177]:
reverse(a , 3)

5-element Array{Int64,1}:
 1
 2
 5
 4
 3

In [178]:
reverse(a , 2 , 4)

5-element Array{Int64,1}:
 1
 4
 3
 2
 5

In [179]:
a = [0 1 2 ; 3 4 5]

2×3 Array{Int64,2}:
 0  1  2
 3  4  5

In [180]:
reverse(a , dims = 2)

2×3 Array{Int64,2}:
 2  1  0
 5  4  3

In [181]:
a[: , end : -1 : 1]

2×3 Array{Int64,2}:
 2  1  0
 5  4  3

### 繰り返す

#### 要素ごとに繰り返す

In [182]:
repeat([0] , 3)

3-element Array{Int64,1}:
 0
 0
 0

In [183]:
repeat([0] , 1  , 3)

1×3 Array{Int64,2}:
 0  0  0

In [184]:
repeat([0] , 1  , 3 , 1)

1×3×1 Array{Int64,3}:
[:, :, 1] =
 0  0  0

In [185]:
repeat([1 2 3] , inner = (1 , 2))

1×6 Array{Int64,2}:
 1  1  2  2  3  3

In [186]:
a = [1 2 ; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [187]:
repeat(a , inner = (1 , 3 , 1))

2×6×1 Array{Int64,3}:
[:, :, 1] =
 1  1  1  2  2  2
 3  3  3  4  4  4

### タイル状に並べる

In [188]:
a = Vector(1:2)

2-element Array{Int64,1}:
 1
 2

In [189]:
repeat(a , 2)

4-element Array{Int64,1}:
 1
 2
 1
 2

In [190]:
repeat(a  ,1 , 2)

2×2 Array{Int64,2}:
 1  1
 2  2

In [191]:
b = [0 1 2]

1×3 Array{Int64,2}:
 0  1  2

In [192]:
repeat(b , 3)

3×3 Array{Int64,2}:
 0  1  2
 0  1  2
 0  1  2

In [193]:
repeat(b , 1 , 3)

1×9 Array{Int64,2}:
 0  1  2  0  1  2  0  1  2

In [194]:
repeat(b , 1 , 3 , 1)

1×9×1 Array{Int64,3}:
[:, :, 1] =
 0  1  2  0  1  2  0  1  2

In [195]:
a = [1 2 3]

1×3 Array{Int64,2}:
 1  2  3

In [196]:
repeat(a , outer = (2 , 2 , 1))

2×6×1 Array{Int64,3}:
[:, :, 1] =
 1  2  3  1  2  3
 1  2  3  1  2  3

In [197]:
repeat(a , inner = (1 , 1 , 2) , outer = (2 , 2))

2×6×2 Array{Int64,3}:
[:, :, 1] =
 1  2  3  1  2  3
 1  2  3  1  2  3

[:, :, 2] =
 1  2  3  1  2  3
 1  2  3  1  2  3

In [198]:
repeat(a , inner = (1 , 1 , 2))

1×3×2 Array{Int64,3}:
[:, :, 1] =
 1  2  3

[:, :, 2] =
 1  2  3

### 回転させる

#### 90度

In [199]:
a = [0 1 ; 3 4]

2×2 Array{Int64,2}:
 0  1
 3  4

In [200]:
rotl90(a) #左に90度

2×2 Array{Int64,2}:
 1  4
 0  3

In [201]:
rotl90(a , 2) #左に180度

2×2 Array{Int64,2}:
 4  3
 1  0

In [202]:
rotr90(a) #右に90度

2×2 Array{Int64,2}:
 3  0
 4  1

In [203]:
rotr90(a , 2) #右に180度

2×2 Array{Int64,2}:
 4  3
 1  0

#### 180度

In [204]:
a = [0 1 ; 3 4]

2×2 Array{Int64,2}:
 0  1
 3  4

In [205]:
rot180(a)

2×2 Array{Int64,2}:
 4  3
 1  0

In [206]:
rot180(a , 2)

2×2 Array{Int64,2}:
 0  1
 3  4

### シフトさせる

In [207]:
a = Vector(1 : 5)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [208]:
circshift(a , 2)

5-element Array{Int64,1}:
 4
 5
 1
 2
 3

In [209]:
a = reshape(1 : 9 , (3 , 3))

3×3 reshape(::UnitRange{Int64}, 3, 3) with eltype Int64:
 1  4  7
 2  5  8
 3  6  9

In [210]:
circshift(a , -1) #上にシフト

3×3 Array{Int64,2}:
 2  5  8
 3  6  9
 1  4  7

In [211]:
circshift(a , 1) #下にシフト

3×3 Array{Int64,2}:
 3  6  9
 1  4  7
 2  5  8

In [212]:
circshift(a , (0 , -1)) #左にシフト

3×3 Array{Int64,2}:
 4  7  1
 5  8  2
 6  9  3

In [213]:
circshift(a , (0 , 1)) #右にシフト

3×3 Array{Int64,2}:
 7  1  4
 8  2  5
 9  3  6

### 最大値(最小値)を取得する

In [214]:
a = reshape(1 : 6 , (2 , 3))

2×3 reshape(::UnitRange{Int64}, 2, 3) with eltype Int64:
 1  3  5
 2  4  6

In [215]:
maximum(a) #最大値

6

In [216]:
minimum(a) #最小値

1

In [217]:
extrema(a) #最大値と最小値の両方

(1, 6)

In [218]:
maximum(a , dims = 1)

1×3 Array{Int64,2}:
 2  4  6

In [219]:
maximum(a , dims = 2)

2×1 Array{Int64,2}:
 5
 6

In [220]:
maximum(a , dims = (1 , 2))

1×1 Array{Int64,2}:
 6

In [221]:
extrema(a , dims = 2)

2×1 Array{Tuple{Int64,Int64},2}:
 (1, 5)
 (2, 6)

### インデックスを取得する

In [222]:
argmax([1 , 2 , 3 , 4]) #最小値はargmin

4

In [223]:
a = [1 4 ; 4 3] #最初の最大値のindex

2×2 Array{Int64,2}:
 1  4
 4  3

In [224]:
argmax(a)

CartesianIndex(2, 1)

In [225]:
a[CartesianIndex(2 , 1)]

4

In [226]:
argmax(a , dims = 1)

1×2 Array{CartesianIndex{2},2}:
 CartesianIndex(2, 1)  CartesianIndex(1, 2)

In [227]:
argmax(a , dims = 2)

2×1 Array{CartesianIndex{2},2}:
 CartesianIndex(1, 2)
 CartesianIndex(2, 1)

In [228]:
argmax(a , dims = (1 , 2))

1×1 Array{CartesianIndex{2},2}:
 CartesianIndex(2, 1)

### 最大値(最小値)とインデックスを取得する

In [229]:
a = [1 4 ; 3 4]

2×2 Array{Int64,2}:
 1  4
 3  4

In [230]:
findmax(a) #最小値はfindmin

(4, CartesianIndex(1, 2))

In [231]:
findmax(a , dims = 1)

([3 4], CartesianIndex{2}[CartesianIndex(2, 1) CartesianIndex(1, 2)])

In [232]:
findmax(a , dims = 2)

([4; 4], CartesianIndex{2}[CartesianIndex(1, 2); CartesianIndex(2, 2)])

In [233]:
findmax(a , dims = (1 , 2))

([4], CartesianIndex{2}[CartesianIndex(1, 2)])

### シャッフルする

In [234]:
using Random

In [235]:
shuffle(1 : 3)

3-element Array{Int64,1}:
 3
 2
 1

In [236]:
a = [1 2 ; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [237]:
a[shuffle(1 : end) , :]

2×2 Array{Int64,2}:
 3  4
 1  2

In [238]:
a[: , shuffle(1:end)]

2×2 Array{Int64,2}:
 2  1
 4  3

In [239]:
shuffle(a)

2×2 Array{Int64,2}:
 2  1
 3  4

#### 二つの配列の対応関係を保ったままシャッフルする

In [240]:
a = Vector(6 : 10)
b = Vector(11 : 15)
idx = shuffle(1 : 5)

5-element Array{Int64,1}:
 4
 1
 2
 5
 3

In [241]:
a[idx]

5-element Array{Int64,1}:
  9
  6
  7
 10
  8

In [242]:
b[idx]

5-element Array{Int64,1}:
 14
 11
 12
 15
 13

### コピーする

In [243]:
a = [1 2 3 ; 4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [244]:
b = copy(a)

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [245]:
a[2 , 2] = 0
a

2×3 Array{Int64,2}:
 1  2  3
 4  0  6

In [246]:
b #変化なし

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [247]:
a = [[1 , 2 , 3] , [4 , 5 , 6]]

2-element Array{Array{Int64,1},1}:
 [1, 2, 3]
 [4, 5, 6]

In [248]:
b = copy(a)

2-element Array{Array{Int64,1},1}:
 [1, 2, 3]
 [4, 5, 6]

In [249]:
c = deepcopy(a)

2-element Array{Array{Int64,1},1}:
 [1, 2, 3]
 [4, 5, 6]

In [250]:
a[1][2] = 0
a

2-element Array{Array{Int64,1},1}:
 [1, 0, 3]
 [4, 5, 6]

In [251]:
b

2-element Array{Array{Int64,1},1}:
 [1, 0, 3]
 [4, 5, 6]

In [252]:
c

2-element Array{Array{Int64,1},1}:
 [1, 2, 3]
 [4, 5, 6]

# 乱数

## 一様分布に従う乱数

In [253]:
rand(2) #0 ~ 1 の一様分布

2-element Array{Float64,1}:
 0.8355180027344449
 0.5664137432915617

In [254]:
rand(Int32 , 3 , 1)

3×1 Array{Int32,2}:
 -1994352922
  -883334872
  1395232195

In [255]:
rand(Float16 , (3 , 3))

3×3 Array{Float16,2}:
 0.6406  0.633    0.6836
 0.4639  0.3115   0.96  
 0.949   0.05762  0.1133

## 要素が Bool の乱数

In [256]:
using Random

In [257]:
bitrand((2 , 2)) #true = 1 , false = 0

2×2 BitArray{2}:
 1  1
 0  1

## 標準正規分布に従う乱数

In [258]:
randn(Float32  ,(2 , 2))

2×2 Array{Float32,2}:
 0.38795  -0.173975
 1.33683   0.055967